-- AddForeignKey
ALTER TABLE "Record" ADD CONSTRAINT "Record_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Record" ADD CONSTRAINT "Record_pakanId_fkey" FOREIGN KEY ("pakanId") REFERENCES "Pakan"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
